export * from './common.model'
export * from './corporation.model'
export * from './job.model'
export * from './location.model'
export * from './student.model'
export * from './lecturer.model'
export * from './user.model'
